openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:80'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/v1/register:
    post:
      summary: 'Регистрация пользователя.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: inventore
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: rabernathy@example.com
                password:
                  type: string
                  description: ''
                  example: 'y4![Im/BU*!0'
                password_confirmation:
                  type: string
                  description: ''
                  example: null
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: 'Авторизация пользователя.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: corrine.stokes@example.net
                password:
                  type: string
                  description: ''
                  example: 'v#IhMq_Ax+t$NZ!,'
              required:
                - email
                - password
      security: []
  /api/v1/abs:
    get:
      summary: 'Получить все объявления постранично.'
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
        -
          in: query
          name: sort_by_price
          description: ''
          example: desc
          required: false
          schema:
            type: string
            description: ''
            example: desc
        -
          in: query
          name: sort_by_created_at
          description: ''
          example: desc
          required: false
          schema:
            type: string
            description: ''
            example: desc
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: ''
                  example: 14
                sort_by_price:
                  type: string
                  description: ''
                  example: at
                sort_by_created_at:
                  type: string
                  description: ''
                  example: laborum
    post:
      summary: 'Создать объявление.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 200 characters.'
                  example: ulfrcpozmkkbghs
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Esse veniam et occaecati mollitia architecto.'
                photos:
                  type: array
                  description: ''
                  example:
                    - ut
                  items:
                    type: string
                price:
                  type: string
                  description: ''
                  example: ducimus
              required:
                - name
                - description
                - photos
                - price
  '/api/v1/abs/{id}':
    get:
      summary: 'Получить объявление.'
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: fields
          description: ''
          example:
            - dolorum
          required: true
          schema:
            type: array
            description: ''
            example:
              - dolorum
            items:
              type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the ab.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
