openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:80'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
  /api/v1/register:
    post:
      summary: 'Регистрация пользователя.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: optio
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: lockman.edyth@example.net
                password:
                  type: string
                  description: ''
                  example: 'V!m;B{G@-k]2'
                password_confirmation:
                  type: string
                  description: ''
                  example: null
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: 'Авторизация пользователя.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: blair92@example.org
                password:
                  type: string
                  description: ''
                  example: 'fJ{yFzY'
              required:
                - email
                - password
      security: []
  /api/v1/abs:
    get:
      summary: 'Получить все объявления постранично.'
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: page
          description: ''
          example: 1
          required: false
          schema:
            type: integer
            description: ''
            example: 1
        -
          in: query
          name: sort_by_price
          description: ''
          example: desc
          required: false
          schema:
            type: string
            description: ''
            example: desc
        -
          in: query
          name: sort_by_created_at
          description: ''
          example: desc
          required: false
          schema:
            type: string
            description: ''
            example: desc
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  abs:
                    data: []
                    meta:
                      current_page: 20
                      first_page_url: 'http://127.0.0.1/api/v1/abs?page=1'
                      from: null
                      last_page: 11
                      last_page_url: 'http://127.0.0.1/api/v1/abs?page=11'
                      next_page_url: null
                      path: 'http://127.0.0.1/api/v1/abs'
                      per_page: 10
                      prev_page_url: 'http://127.0.0.1/api/v1/abs?page=19'
                      to: null
                      total: 106
                properties:
                  abs:
                    type: object
                    properties:
                      data:
                        type: array
                        example: []
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 20
                          first_page_url:
                            type: string
                            example: 'http://127.0.0.1/api/v1/abs?page=1'
                          from:
                            type: string
                            example: null
                          last_page:
                            type: integer
                            example: 11
                          last_page_url:
                            type: string
                            example: 'http://127.0.0.1/api/v1/abs?page=11'
                          next_page_url:
                            type: string
                            example: null
                          path:
                            type: string
                            example: 'http://127.0.0.1/api/v1/abs'
                          per_page:
                            type: integer
                            example: 10
                          prev_page_url:
                            type: string
                            example: 'http://127.0.0.1/api/v1/abs?page=19'
                          to:
                            type: string
                            example: null
                          total:
                            type: integer
                            example: 106
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                page:
                  type: integer
                  description: ''
                  example: 20
                sort_by_price:
                  type: string
                  description: ''
                  example: inventore
                sort_by_created_at:
                  type: string
                  description: ''
                  example: et
    post:
      summary: 'Создать объявление.'
      operationId: ''
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 200 characters.'
                  example: urpfu
                description:
                  type: string
                  description: 'Must not be greater than 1000 characters.'
                  example: 'Et omnis perspiciatis vel ipsum aut inventore molestiae.'
                photos:
                  type: array
                  description: ''
                  example:
                    - mollitia
                  items:
                    type: string
                price:
                  type: string
                  description: ''
                  example: quia
              required:
                - name
                - description
                - photos
                - price
  '/api/v1/abs/{id}':
    get:
      summary: 'Получить объявление.'
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: fields
          description: ''
          example:
            - quia
          required: true
          schema:
            type: array
            description: ''
            example:
              - quia
            items:
              type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  ab:
                    abId: 1
                    name: johkvmpxr
                    price: '1234.00'
                    photoLink:
                      id: 1
                      ab_id: 1
                      link: '1'
                      created_at: '2024-07-29T05:17:25.000000Z'
                      updated_at: '2024-07-29T05:17:25.000000Z'
                properties:
                  ab:
                    type: object
                    properties:
                      abId:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: johkvmpxr
                      price:
                        type: string
                        example: '1234.00'
                      photoLink:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          ab_id:
                            type: integer
                            example: 1
                          link:
                            type: string
                            example: '1'
                          created_at:
                            type: string
                            example: '2024-07-29T05:17:25.000000Z'
                          updated_at:
                            type: string
                            example: '2024-07-29T05:17:25.000000Z'
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                fields:
                  type: object
                  description: ''
                  example: null
                  properties: {  }
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the ab.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
